"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, HeartHandshake, Sparkles, GraduationCap, Utensils, ShieldCheck, Mail, Phone, MapPin, CheckCircle2, HandHeart, Stars } from "lucide-react";

export default function SponsorPage(){
  const [sent,setSent]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const name=String(data.get("name")||"");const email=String(data.get("email")||"");const phone=String(data.get("phone")||"");const country=String(data.get("country")||"");const interest=String(data.get("interest")||"");const message=String(data.get("message")||"");const subject=encodeURIComponent("Child sponsorship enquiry — "+name);const body=encodeURIComponent("Hello Papa’s Love Children’s Ministry,\n\nI’m interested in learning more about sponsoring a child. Please contact me with further information.\n\nName: "+name+"\nEmail: "+email+"\nPhone / WhatsApp: "+phone+"\nCountry: "+country+"\nSponsorship interest: "+interest+"\n\nMessage: "+(message||"I would appreciate more details about the sponsorship process.")+"\n\nThank you.");window.location.href="mailto:papaslovechildrenministry@gmail.com?subject="+subject+"&body="+body;setSent(true);}
  return <main className="sponsor-page">
    <section className="sponsor-hero"><div className="sponsor-orb sponsor-orb-a"/><div className="sponsor-orb sponsor-orb-b"/><div className="sponsor-hero-pattern"/><div className="sponsor-wrap sponsor-hero-inner"><div className="sponsor-hero-copy"><span className="sponsor-kicker"><Sparkles size={15}/> A LITTLE LOVE CAN CHANGE A LIFETIME</span><h1>Be the <span>steady light</span><br/>in a child’s story.</h1><p>Become part of a child’s journey at Papa’s Love Children’s Ministry. Your interest today can help create a future filled with safety, learning, nourishment and hope.</p><a className="sponsor-hero-btn" href="#sponsor-form">I’m interested in sponsoring <ArrowRight size={18}/></a><div className="sponsor-trust"><HeartHandshake size={17}/> A personal conversation. Clear guidance. A meaningful connection.</div></div><div className="sponsor-hero-art"><div className="sponsor-photo-frame"><img src="/images/papas-love-about-us.png" alt="Children supported by Papa’s Love Children’s Ministry"/><div className="sponsor-photo-shade"/><div className="sponsor-photo-caption"><span>HOPE GROWS</span><strong>When we care<br/>together.</strong></div></div><div className="sponsor-float sponsor-float-top"><span><HeartHandshake size={17}/></span><div><b>One caring heart</b><small>Can make a lasting difference</small></div></div><div className="sponsor-float sponsor-float-bottom"><Stars size={18}/><b>65 children</b><small>surrounded by care</small></div></div></div><div className="sponsor-hero-wave"/></section>
    <section className="sponsor-why sponsor-wrap"><div className="sponsor-section-heading"><span className="sponsor-kicker-blue">THE GIFT OF SHOWING UP</span><h2>More than support.<br/><span>It’s belonging.</span></h2><p>Sponsorship is an opportunity to stand beside a child as they grow. Our team will speak with you personally, explain current needs and help you understand the ways you can make a difference.</p></div><div className="sponsor-benefits"><article><div className="sponsor-benefit-icon pink"><GraduationCap/></div><h3>Learning with confidence</h3><p>Help a child access school essentials, learning opportunities and encouragement to keep dreaming.</p></article><article><div className="sponsor-benefit-icon blue"><Utensils/></div><h3>Care for everyday needs</h3><p>Support the nourishment, wellbeing and practical care children need to thrive each day.</p></article><article><div className="sponsor-benefit-icon gold"><HeartHandshake/></div><h3>A connection that matters</h3><p>Learn how sponsorship works and how our ministry keeps you informed about the impact of your support.</p></article></div></section>
    <section className="sponsor-form-section" id="sponsor-form"><div className="sponsor-form-glow"/><div className="sponsor-wrap sponsor-form-layout"><div className="sponsor-form-intro"><span className="sponsor-kicker"><HandHeart size={15}/> LET’S START A CONVERSATION</span><h2>Your heart for a child<br/><span>starts here.</span></h2><p>Share a few details and our team will follow up to answer your questions, explain the sponsorship options and help you decide what feels right for you.</p><div className="sponsor-contact-points"><p><Mail size={17}/> papaslovechildrenministry@gmail.com</p><p><Phone size={17}/> +256 774615784 · +256709196703</p><p><MapPin size={17}/> Naama Village, Mityana, Uganda</p></div><div className="sponsor-privacy"><ShieldCheck size={18}/> Your details are for responding to your enquiry and will be treated with care.</div></div><form className="sponsor-form" onSubmit={submit}><div className="sponsor-form-top"><span>SPONSORSHIP ENQUIRY</span><small><span className="sponsor-required">*</span> Required fields</small></div><h3>Tell us about yourself</h3><p className="sponsor-form-lead">No commitment is required. We’re happy to answer every question.</p><div className="sponsor-fields"><label>Full name <span>*</span><input name="name" autoComplete="name" placeholder="Your full name" required/></label><label>Email address <span>*</span><input name="email" type="email" autoComplete="email" placeholder="you@example.com" required/></label><label>Phone / WhatsApp <span>*</span><input name="phone" type="tel" autoComplete="tel" placeholder="Include country code" required/></label><label>Country <span>*</span><input name="country" autoComplete="country-name" placeholder="Where are you based?" required/></label><label className="sponsor-full-field">How would you like to help? <span>*</span><select name="interest" defaultValue="" required><option value="" disabled>Select your interest</option><option>Explore sponsoring one child</option><option>Explore supporting more than one child</option><option>Learn about monthly sponsorship</option><option>Learn about one-time or flexible support</option><option>I’d like to discuss the options first</option></select></label><label className="sponsor-full-field">Anything you’d like us to know? <small>(Optional)</small><textarea name="message" rows={4} placeholder="Share questions, preferences or the best time to reach you…"/></label></div><button className="sponsor-submit" type="submit">Send my enquiry <ArrowRight size={18}/></button><p className="sponsor-form-note"><ShieldCheck size={14}/> Your email app will open with your enquiry ready to send.</p>{sent&&<p className="sponsor-form-status" role="status"><CheckCircle2 size={16}/> Your enquiry is prepared. Please send it from your email app so our team can receive it.</p>}</form></div></section>
    <section className="sponsor-final-cta"><div className="sponsor-cta-rings"/><div className="sponsor-wrap sponsor-cta-inner"><span className="sponsor-kicker"><Sparkles size={15}/> EVERY CHILD DESERVES TO BE SEEN</span><h2>Let’s make room for<br/><span>one more bright future.</span></h2><p>Take the first step. We’ll walk you through the rest, with care and clarity.</p><a href="#sponsor-form" className="sponsor-cta-btn">Start your sponsorship enquiry <ArrowRight size={18}/></a><small>With gratitude, Papa’s Love Children’s Ministry · Uganda</small></div></section>
  </main>;
}
