"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Heart, HandHeart, X, ChevronLeft, ChevronRight, Images, Sparkles } from "lucide-react";


const filters=["All moments","Children","Our Home","Daily Care","Learning"];
export default function GalleryPage(){const [photos,setPhotos]=useState<any[]>([]);const [filter,setFilter]=useState("All moments");const [active,setActive]=useState<number|null>(null);useEffect(()=>{const endpoint=(process.env.NEXT_PUBLIC_API_URL?.trim()||"https://plcmbackend.up.railway.app/graphql").replace(/\/$/,"");const api=endpoint.endsWith("/graphql")?endpoint:endpoint+"/graphql";fetch(api,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:"{ publicGallery { id src title caption category position } }"})}).then(r=>r.json()).then(p=>{if(!p.errors&&Array.isArray(p.data?.publicGallery))setPhotos(p.data.publicGallery)}).catch(()=>{});},[]);const visible=photos.map((p,i)=>({...p,index:i})).filter(p=>filter==="All moments"||p.category===filter);const move=(delta:number)=>setActive(i=>i===null?null:(i+delta+photos.length)%photos.length);return <main className="gallery-page">
<section className="gallery-hero"><div className="gallery-hero-photo"/><div className="gallery-hero-shade"/><div className="gallery-hero-orbit orbit-a"/><div className="gallery-hero-orbit orbit-b"/><div className="gallery-wrap gallery-hero-inner"><span className="gallery-eyebrow"><i/> THE HEART OF PAPA’S LOVE</span><h1>More than pictures.<br/><em>Moments of hope.</em></h1><p>Meet the smiles, the everyday care, the learning and the little moments that make a family. Every photograph holds a reminder: every child is worthy of love and a future.</p><div className="gallery-hero-actions"><a className="gallery-btn gallery-btn-gold" href="/donate"><Heart size={17} fill="currentColor"/> Donate with love</a><a className="gallery-btn gallery-btn-outline" href="/sponsor"><HandHeart size={17}/> Sponsor a child</a></div><div className="gallery-hero-foot"><span><b>65</b> children in our daily care</span><span className="gallery-foot-divider"/><span>Naama Village · Uganda</span></div></div><div className="gallery-hero-label"><Images size={18}/> A glimpse into our family</div></section>
<section className="gallery-intro gallery-wrap"><div><span className="gallery-kicker">LIFE AT PAPA’S LOVE</span><h2>Small moments.<br/><em>Infinite worth.</em></h2></div><p>There is a story behind every smile: a child finding belonging, a meal shared, a new lesson discovered, a safe place to rest. Explore our moments—and if one moves your heart, you can help make more of them possible.</p></section>
<section className="gallery-showcase" id="gallery-photos"><div className="gallery-wrap"><div className="gallery-toolbar"><div><span className="gallery-kicker">THE PHOTO STORY</span><h2>Our days, through <em>their eyes.</em></h2></div><span className="gallery-count"><Images size={16}/> {visible.length} moments</span></div><div className="gallery-filters" role="group" aria-label="Filter gallery photos">{filters.map(f=><button key={f} type="button" className={filter===f?"gallery-filter active":"gallery-filter"} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="gallery-masonry">{visible.map((photo,j)=><button type="button" key={photo.src} className={`gallery-tile gallery-tile-${j%6}`} onClick={()=>setActive(photo.index)} aria-label={`View photo: ${photo.title}`}><img src={photo.src} alt={photo.title}/><span className="gallery-tile-shade"/><span className="gallery-tile-caption"><small>{photo.category}</small><b>{photo.title}</b><i>View moment ↗</i></span></button>)}</div><p className="gallery-note"><Sparkles size={15}/> Each image is a glimpse of the care, dignity and possibility we want every child to experience.</p></div></section>
<section className="gallery-quote"><div className="gallery-wrap gallery-quote-inner"><span>“</span><div><p>Every child deserves to be seen not as a need, but as a <em>whole person full of promise.</em></p><small>OUR HEART · OUR COMMITMENT</small></div><Heart className="gallery-quote-heart"/></div></section>
<section className="gallery-cta"><div className="gallery-cta-pattern"/><div className="gallery-wrap gallery-cta-inner"><div className="gallery-cta-art"><img src="/images/papas-carousel-children.png" alt="Children at Papa’s Love Children’s Ministry"/><span className="gallery-cta-sticker"><Heart fill="currentColor"/> Be part of<br/><b>their next chapter.</b></span></div><div className="gallery-cta-copy"><span className="gallery-eyebrow"><i/> THE STORY IS STILL BEING WRITTEN</span><h2>Help create more<br/><em>moments like these.</em></h2><p>For the 65 children in our care, your kindness can help make meals dependable, learning possible, and daily life safer and more joyful. You can give once, sponsor a child, or share our story.</p><div className="gallery-cta-actions"><a className="gallery-btn gallery-btn-gold" href="/donate">Donate today <ArrowRight size={17}/></a><a className="gallery-btn gallery-btn-outline" href="/sponsor">Sponsor a child <HandHeart size={17}/></a></div><small>Thank you for seeing their potential—and standing with them.</small></div></div></section>
{active!==null&&<div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label="Photo viewer" onClick={()=>setActive(null)}><button className="gallery-lightbox-close" aria-label="Close photo viewer" onClick={()=>setActive(null)}><X/></button><button className="gallery-lightbox-arrow prev" aria-label="Previous photo" onClick={e=>{e.stopPropagation();move(-1)}}><ChevronLeft/></button><figure onClick={e=>e.stopPropagation()}><img src={photos[active].src} alt={photos[active].title}/><figcaption><small>{photos[active].category}</small><b>{photos[active].title}</b><span>{photos[active].caption}</span><i>{active+1} / {photos.length}</i></figcaption></figure><button className="gallery-lightbox-arrow next" aria-label="Next photo" onClick={e=>{e.stopPropagation();move(1)}}><ChevronRight/></button></div>}
</main>}
