"use client";
import { useState } from "react";
import { ArrowRight, BookOpen, Heart, HandHeart, Utensils, GraduationCap, House, UsersRound, Sparkles, CalendarDays, ChevronRight } from "lucide-react";

const stories=[
 {category:"Daily Care",title:"A place where every child belongs",excerpt:"At Papa’s Love, care is more than a meal or a bed. It is the everyday promise that each child is seen, welcomed and encouraged to dream.",image:"/images/papas-love-about-us.png",icon:Heart,tag:"Our Home",featured:true},
 {category:"Nutrition",title:"Nourishing little bodies, growing big dreams",excerpt:"Nutritious meals help children feel stronger, focus in class and enjoy the simple joy of growing up. Help us keep dependable meals on the table for the 65 children in our care.",image:"/images/papas-carousel-food.png",icon:Utensils,tag:"Daily Care"},
 {category:"Education",title:"Every school day opens a new door",excerpt:"Books, school supplies, encouragement and consistent support help children take confident steps toward a brighter future.",image:"/images/papas-carousel-school-supplies.png",icon:GraduationCap,tag:"Learning"},
 {category:"Community",title:"A safe home. A stronger tomorrow.",excerpt:"A stable, caring environment gives vulnerable children room to heal, build friendships and discover their gifts.",image:"/images/shelter.jpg",icon:House,tag:"Protection"},
 {category:"Children",title:"Small moments. Lasting hope.",excerpt:"From shared laughter to learning together, everyday moments remind us why every child deserves dignity, attention and opportunity.",image:"/images/papas-carousel-children.png",icon:UsersRound,tag:"Together"},
 {category:"Wellbeing",title:"Care that reaches beyond today",excerpt:"Supporting children means caring for their wellbeing today while helping them build the confidence and skills they will carry into tomorrow.",image:"/images/t3.jpeg",icon:Heart,tag:"Our Mission"}
];
const categories=["All stories","Daily Care","Nutrition","Education","Community","Children","Wellbeing"];
export default function NewsPage(){const [active,setActive]=useState("All stories");const filtered=active==="All stories"?stories:stories.filter(s=>s.category===active);return <main className="news-page">
<section className="news-hero"><div className="news-hero-glow news-glow-one"/><div className="news-hero-glow news-glow-two"/><div className="news-hero-dots"/><div className="wrap news-hero-layout"><div className="news-hero-copy"><span className="news-eyebrow"><Sparkles size={15}/> STORIES OF HOPE & PROGRESS</span><h1>Good things are <span>growing.</span><br/>Come see what’s happening.</h1><p>Stories from our home in Naama, Mityana—where practical care, learning and love help children move toward brighter futures.</p><div className="news-hero-actions"><a className="btn news-btn-gold" href="#latest"><BookOpen size={17}/> Explore Updates <ArrowRight size={17}/></a><a className="btn news-btn-glass" href="/donate"><Heart size={17}/> Make a Difference</a></div><div className="news-hero-note"><span className="news-note-dot"/> Updates from Papa’s Love Children’s Ministry <span className="news-note-sep">•</span> Naama, Uganda</div></div><div className="news-hero-visual"><div className="news-photo-main"><img src="/images/t3.jpeg" alt="Children connected through the work of Papa’s Love Children’s Ministry"/></div><div className="news-photo-small"><img src="/images/papas-carousel-children.png" alt="Children sharing a moment together"/></div><div className="news-float-card"><span className="news-float-icon"><Heart size={19} fill="currentColor"/></span><div><strong>65 children</strong><small>in our daily care</small></div><span className="news-float-spark">✦</span></div><span className="news-orbit news-orbit-a"/><span className="news-orbit news-orbit-b"/></div></div><div className="news-hero-wave"/></section>
<section className="news-intro wrap"><div><span className="news-section-kicker">THE HEART BEHIND THE HEADLINES</span><h2>Every update tells a story<br/><span>of care in action.</span></h2></div><p>Here you’ll find ministry highlights, reflections and ways to stand alongside children in our care. These are evergreen introductory stories about our ongoing work; we’ll add dated reports and event updates as they are shared by the ministry.</p></section>
<section className="news-list-section" id="latest"><div className="wrap"><div className="news-list-heading"><div><span className="news-section-kicker">FROM OUR MINISTRY</span><h2>News & <span>Updates</span></h2><p>Little steps of progress. Big reasons to keep believing.</p></div><div className="news-count"><strong>{filtered.length.toString().padStart(2,"0")}</strong><span>Stories</span></div></div><div className="news-filters" aria-label="Filter stories">{categories.map(c=><button type="button" key={c} className={active===c?"news-filter active":"news-filter"} onClick={()=>setActive(c)}>{c}</button>)}</div><div className="news-grid">{filtered.map((story,i)=>{const Icon=story.icon;return <article className={story.featured&&active==="All stories"?"news-card news-card-featured":"news-card"} key={story.title}><a className="news-card-image" href="/donate" aria-label={"Support ministry work: "+story.title}><img src={story.image} alt={story.title}/><span className="news-card-tag">{story.tag}</span><span className="news-card-arrow"><ArrowRight size={18}/></span></a><div className="news-card-body"><div className="news-card-meta"><span><Icon size={14}/>{story.category}</span><span><CalendarDays size={14}/> Ongoing</span></div><h3>{story.title}</h3><p>{story.excerpt}</p><a href="/donate" className="news-read-link">Be part of this story <ChevronRight size={16}/></a></div></article>})}</div></div></section>
<section className="news-quote-band"><div className="wrap news-quote-inner"><span className="news-quote-mark">“</span><p>Let us not love with words or speech but with actions and in truth.</p><strong>1 John 3:18</strong><span className="news-quote-decor">✳</span></div></section>
<section className="news-cta"><div className="news-cta-pattern"/><div className="wrap news-cta-inner"><div className="news-cta-image"><img src="/images/papas-carousel-children.png" alt="Children at Papa’s Love Children’s Ministry"/></div><div className="news-cta-copy"><span className="news-eyebrow"><Heart size={15}/> YOU CAN HELP WRITE THE NEXT CHAPTER</span><h2>Let’s make the next story a brighter one.</h2><p>Your generosity helps provide meals, learning support, safety and steady care for children who need someone in their corner.</p><div className="news-hero-actions"><a className="btn news-btn-gold" href="/donate"><Heart size={17}/> Donate Now <ArrowRight size={17}/></a><a className="btn news-btn-outline" href="/sponsor"><HandHeart size={17}/> Sponsor a Child</a></div><a className="news-gofund-link" href="https://gofund.me/806b43834" target="_blank" rel="noopener noreferrer">Support our GoFundMe campaign <ArrowRight size={15}/></a></div></div></section>
</main>}
