import { ArrowRight, Heart, Utensils, GraduationCap, Droplets, ShieldCheck, Stethoscope, Shirt, HandHeart, Sparkles, UsersRound } from "lucide-react";

const causes = [
  { id:"meals", number:"01", title:"A Full Plate, Every Day", category:"NOURISHMENT", image:"/images/food.jpg", icon:Utensils, accent:"coral", lead:"Food & daily nutrition", description:"For a child, a dependable meal means more than a full stomach. It means energy to learn, strength to grow, and the comfort of knowing tomorrow’s food is not a question mark.", impact:"Help put nutritious food and clean drinking water on the table.", action:"Help feed a child" },
  { id:"education", number:"02", title:"Open the Door to Learning", category:"EDUCATION", image:"/images/school.jpeg", icon:GraduationCap, accent:"gold", lead:"School fees & learning", description:"A uniform, books, pens and school fees can help turn a child’s curiosity into opportunity. Give children the tools and encouragement to keep learning.", impact:"Support school access, scholastic materials and learning.", action:"Invest in learning" },
  { id:"water", number:"03", title:"Clean Water. Healthier Tomorrows.", category:"CLEAN WATER", image:"/images/water.jpg", icon:Droplets, accent:"aqua", lead:"Safe water & hygiene", description:"Clean water protects health, supports hygiene and makes everyday life safer. Help make this essential part of care more dependable for the children.", impact:"Help provide safe drinking water and hygiene essentials.", action:"Give clean water" },
  { id:"shelter", number:"04", title:"A Safe Place to Belong", category:"SAFETY & SHELTER", image:"/images/shelter.jpg", icon:ShieldCheck, accent:"lavender", lead:"Shelter & protection", description:"Every child deserves a place where they can rest without fear, feel welcomed, and be treated with dignity. Your support helps sustain a caring, protective home.", impact:"Strengthen daily care, safety and a sense of family.", action:"Support a safe home" },
  { id:"health", number:"05", title:"Healthy Children Can Thrive", category:"HEALTH & WELLBEING", image:"/images/t3.jpeg", icon:Stethoscope, accent:"rose", lead:"Healthcare & wellbeing", description:"When children are unwell, timely care matters. Help us respond to everyday health needs and support children’s physical and emotional wellbeing.", impact:"Help with essential medicines, check-ups and care.", action:"Support children’s health" },
  { id:"essentials", number:"06", title:"Dignity in Every Little Thing", category:"CLOTHING & ESSENTIALS", image:"/images/papas-carousel-children.png", icon:Shirt, accent:"blue", lead:"Clothing & daily essentials", description:"Clean clothes, shoes and personal-care items help children feel comfortable, confident and ready to take part in school and community life.", impact:"Provide clothing, shoes and everyday necessities.", action:"Give everyday essentials" },
  { id:"future", number:"07", title:"Help a Child Dream Bigger", category:"SPONSORSHIP", image:"/images/papas-carousel-school-supplies.png", icon:Sparkles, accent:"violet", lead:"Sponsorship & future", description:"Consistent support helps a child’s needs be met over time—not just today. Stand alongside a child as they learn, grow and discover what is possible.", impact:"Build a steadier foundation of care and opportunity.", action:"Sponsor a child" },
];
const campaign="#";

export default function CausesPage(){return <main className="causes-page">
<section className="causes-hero"><div className="causes-hero-image" role="img" aria-label="Children at Papa’s Love Children Ministry" /><div className="causes-hero-overlay"/><div className="causes-hero-sun"/><div className="causes-wrap causes-hero-content"><span className="causes-eyebrow"><i/> LOVE IN ACTION · NAAMA, UGANDA</span><h1>Every child deserves<br/>a chance to <em>shine.</em></h1><p>Behind every cause is a child with a name, a laugh, a dream—and a future worth showing up for. Your kindness can help make the essentials of childhood possible.</p><div className="causes-hero-actions"><a className="causes-button causes-button-gold" href="#our-causes">Explore the causes <ArrowRight size={17}/></a><a className="causes-button causes-button-glass" href="/donate"><Heart size={16}/> Give with love</a></div><div className="causes-hero-caption"><span className="caption-dot"/> Papa’s Love Children’s Ministry <b>•</b> Since 2018</div></div><div className="causes-hero-stamp"><Heart fill="currentColor"/><span>Little acts.<br/><b>Lasting love.</b></span></div></section>
<section className="causes-intro causes-wrap"><div><span className="causes-kicker">WHERE YOUR KINDNESS GOES</span><h2>Not just a donation.<br/><em>A difference they can feel.</em></h2></div><p>We care for 65 children every day. Their needs are real and wonderfully human: food to eat, water to drink, a safe place to sleep, the chance to learn, and people who believe in them. Choose a cause close to your heart and help us keep showing up.</p></section>
<section className="causes-impact"><div className="causes-wrap causes-impact-grid"><div className="causes-impact-label"><span className="causes-kicker">THE HEART OF OUR WORK</span><h2>65 children.<br/><em>One caring family.</em></h2></div><div className="causes-impact-stat"><strong>65<span>+</span></strong><b>Children cared for daily</b><small>Each one deserves to be nourished, protected and encouraged.</small></div><div className="causes-impact-stat"><strong>2018</strong><b>Rooted in love</b><small>Serving children with compassion in Naama, Mityana.</small></div><div className="causes-impact-stat"><strong>1</strong><b>Shared promise</b><small>Every child matters. Every act of care counts.</small></div></div></section>
<section className="causes-list-section" id="our-causes"><div className="causes-wrap"><div className="causes-heading"><span className="causes-kicker">OUR CAUSES</span><h2>Choose the hope<br/><em>you want to help grow.</em></h2><p>Every cause is part of the same promise: children should not have to face life’s hardest moments alone.</p><div className="causes-heading-flower" aria-hidden="true">✳</div></div><div className="causes-grid">{causes.map((cause)=><article className={`cause-feature cause-${cause.accent}`} key={cause.id}><div className="cause-feature-image"><img src={cause.image} alt={cause.lead}/><span className="cause-number">{cause.number}</span><span className="cause-feature-icon"><cause.icon size={20}/></span></div><div className="cause-feature-copy"><span className="cause-category">{cause.category}</span><h3>{cause.title}</h3><p>{cause.description}</p><div className="cause-impact-note"><span>YOUR GIFT CAN</span>{cause.impact}</div><a className="cause-donate-link" href={cause.id==="future"?"/sponsor":"/donate#ways-to-give"}>{cause.action}<span><ArrowRight size={17}/></span></a></div></article>)}</div></div></section>
<section className="causes-quote-band"><div className="causes-wrap causes-quote-inner"><span className="causes-quote-mark">“</span><div><p>Sometimes the most powerful thing we can give a child is the simple assurance: <em>you are not forgotten.</em></p><small>— Papa’s Love Children’s Ministry</small></div><div className="causes-quote-heart">♡</div></div></section>
<section className="causes-final"><div className="causes-final-pattern"/><div className="causes-wrap causes-final-inner"><div className="causes-final-art"><img src="/images/papas-carousel-children.png" alt="Children together at Papa’s Love Children Ministry"/><span className="causes-final-note"><Heart fill="currentColor"/> Your kindness<br/><b>belongs here.</b></span></div><div className="causes-final-copy"><span className="causes-eyebrow"><i/> BE PART OF THEIR STORY</span><h2>One kind choice<br/>can change <em>so much.</em></h2><p>You may never meet the child whose day you brighten. But a meal, a school supply, safe water or a steady act of care can remind them that the world still holds people who believe in their future.</p><div className="causes-final-actions"><a className="causes-button causes-button-gold" href="/donate">Make a donation <Heart size={16} fill="currentColor"/></a><a className="causes-button causes-button-light" href={campaign} target="_blank" rel="noopener noreferrer">Support our fundraiser <ArrowRight size={16}/></a></div><small>Thank you for seeing them. Thank you for caring.</small></div></div></section>
</main>}
