"use client";
import { ArrowRight, Heart, ShieldCheck, Copy, Check, Smartphone, Landmark, Globe2, Utensils, UsersRound, GraduationCap } from "lucide-react";
import { useState } from "react";

const campaignUrl = "#";
function CopyValue({value}:{value:string}) { const [copied,setCopied]=useState(false); return <button className="donate-copy" onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}}} aria-label={"Copy "+value}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?"Copied":"Copy"}</span></button>; }
function PayCard({kind,title,subtitle,children,logo}:{kind:string;title:string;subtitle:string;children:React.ReactNode;logo:React.ReactNode}) { return <article className={"pay-card "+kind}><div className="pay-card-top"><div className="pay-logo">{logo}</div><span className="pay-type">{subtitle}</span></div><h3>{title}</h3>{children}</article>; }
export default function DonatePage(){return <main className="donate-page">

<section className="donate-hero"><div className="donate-orb orb-one"/><div className="donate-orb orb-two"/><div className="donate-hero-inner"><div className="donate-hero-copy"><span className="donate-eyebrow"><Heart size={14} fill="currentColor"/> GIVE HOPE. CHANGE A CHILD’S STORY.</span><h1>Your kindness can put <span>hope on the table.</span></h1><p>Help us provide daily meals, education, healthcare and a safe, loving home for the 65 children in our care in Naama, Mityana, Uganda.</p><div className="donate-hero-actions"><a href="#ways-to-give" className="donate-primary">Choose how to give <ArrowRight size={17}/></a><a href={campaignUrl} target="_blank" rel="noopener noreferrer" className="donate-secondary">Give online <Globe2 size={16}/></a></div><div className="donate-trust"><ShieldCheck size={17}/> Every gift helps make practical care possible</div></div><div className="donate-hero-art"><div className="hero-art-glow"/><div className="hero-art-card"><div className="hero-art-heart"><Heart fill="currentColor" size={31}/></div><span className="art-label">YOUR GIFT</span><strong>Love in<br/>action.</strong><div className="art-lines"><i/><i/><i/></div><div className="art-bottom"><span>HOPE • CARE • FUTURE</span><b>♥</b></div></div><div className="floating-note note-meals"><Utensils size={17}/> A meal today</div><div className="floating-note note-future"><GraduationCap size={18}/> A brighter tomorrow</div></div></div></section>
<section className="donate-impact"><div><UsersRound/><b>65 children</b><span>count on daily care</span></div><div><Heart/><b>One community</b><span>many ways to help</span></div><div><ShieldCheck/><b>Every contribution</b><span>makes a difference</span></div></section>
<section className="ways-section" id="ways-to-give"><div className="donate-section-head"><span className="donate-kicker">WAYS TO GIVE</span><h2>Choose the way that works <span>best for you.</span></h2><p>Whether you give from Uganda or abroad, your generosity helps children feel safe, nourished and valued.</p></div><div className="pay-grid">
<PayCard kind="mtn" title="MTN Mobile Money" subtitle="UGANDA • MOBILE MONEY" logo={<span className="mtn-mark">MTN</span>}><div className="pay-detail-label">Send to this number</div><div className="pay-value">+256 774615784 <CopyValue value="+256774615784"/></div><div className="pay-name"><small>Account name</small><b>JJUUKO SHAFIC</b></div><div className="pay-hint"><Smartphone size={15}/> Use Mobile Money → Send Money</div></PayCard>
<PayCard kind="airtel" title="Airtel Money" subtitle="UGANDA • MOBILE MONEY" logo={<span className="airtel-mark"><i/>airtel</span>}><div className="pay-detail-label">Send to this number</div><div className="pay-value">+256709196703 <CopyValue value="+256709196703"/></div><div className="pay-name"><small>Account name</small><b>JJUUKO SHAFIC</b></div><div className="pay-hint"><Smartphone size={15}/> Use Airtel Money → Send Money</div></PayCard>
<PayCard kind="equity" title="Bank Transfer" subtitle="BANK • UGANDA" logo={<span className="equity-mark"><i/>EQUITY</span>}><div className="pay-detail-label">Bank</div><div className="pay-value">Equity Bank Uganda</div><div className="pay-name"><small>Account name</small><b>JJUUKO SHAFIC</b></div><div className="pay-account"><span>Account number</span><b>1016102900637</b><CopyValue value="1016102900637"/></div><div className="pay-account"><span>SWIFT code</span><b>EQBLUGKA</b><CopyValue value="EQBLUGKA"/></div><div className="pay-account"><span>Branch Name</span><b>Mityana</b><CopyValue value="Mityana"/></div><div className="pay-hint"><Landmark size={15}/> Add “Papas Love Donation” as reference</div></PayCard>
<PayCard kind="western" title="Western Union" subtitle="INTERNATIONAL • CASH PICKUP" logo={<span className="wu-mark"><b>WU</b><i>WESTERN UNION</i></span>}><div className="pay-detail-label">Receiver’s name</div><div className="pay-value">JJUUKO SHAFIC</div><div className="pay-name"><small>Country / City</small><b>Uganda · Kampala</b></div><div className="pay-account"><span>Telephone</span><b>+256774615784</b><CopyValue value="+256774615784"/></div><div className="pay-hint"><Globe2 size={15}/> Share the transfer details with us</div></PayCard><PayCard kind="remitly" title="Remitly & World Remit" subtitle="INTERNATIONAL • MONEY TRANSFER" logo={<span className="remitly-mark"><i>↗</i><b>remitly</b></span>}><div className="pay-detail-label">Recipient’s name</div><div className="pay-value">JJUUKO SHAFIC <CopyValue value="JJUUKO SHAFIC"/></div><div className="pay-name"><small>Country</small><b>Uganda</b></div><div className="pay-account"><span>City</span><b>Mityana</b><CopyValue value="Mityana"/></div><div className="pay-account"><span>Telephone</span><b>+256774615784</b><CopyValue value="+256774615784"/></div><div className="pay-hint"><Globe2 size={15}/> Select Uganda and enter the recipient details in Remitly</div></PayCard>
</div></section>
<section className="online-section"><div className="online-copy"><span className="donate-kicker">DONATE ONLINE</span><h2>Give from anywhere in the world.</h2><p>Support our active GoFundMe fundraiser through a secure online giving experience. Every contribution helps us keep meals, care and opportunity within reach.</p><a className="online-button" href={campaignUrl} target="_blank" rel="noopener noreferrer"><Heart size={17} fill="currentColor"/> Donate on GoFundMe <ArrowRight size={17}/></a><small>Opens our official fundraiser in a new tab.</small></div><div className="online-visual"><div className="online-badge"><Heart fill="currentColor" size={20}/> YOUR SUPPORT MATTERS</div><div className="online-big">Give a little.<br/><span>Change a lot.</span></div><div className="online-chips"><span>Meals</span><span>Education</span><span>Protection</span></div></div></section>
<section className="campaigns-section"><div className="donate-section-head"><span className="donate-kicker">ONGOING FUNDRAISER</span><h2>Be part of a child’s <span>brighter tomorrow.</span></h2><p>Join supporters who are helping Papa’s Love Children’s Ministry meet the everyday needs of vulnerable children.</p></div><article className="fundraiser-card"><div className="fundraiser-image"><img src="/images/papas-love-about-us.png" alt="Children at Papa’s Love Children Ministry"/><span className="fundraiser-tag">ACTIVE CAMPAIGN</span></div><div className="fundraiser-copy"><span className="fundraiser-platform">GOFUNDME FUNDRAISER</span><h3>Help Feed and Care for 65 Children</h3><p>Your support helps provide nutritious daily meals and essential care for children who deserve safety, dignity and a chance to thrive.</p><div className="fundraiser-needs"><span><Utensils size={15}/> Daily meals</span><span><GraduationCap size={15}/> Learning</span><span><Heart size={15}/> Care & safety</span></div><a href={campaignUrl} target="_blank" rel="noopener noreferrer" className="fundraiser-button">View & support campaign <ArrowRight size={17}/></a></div></article></section>
<section className="donate-final"><div className="donate-final-inner"><div className="final-heart"><Heart fill="currentColor"/></div><span className="donate-kicker">YOUR GENEROSITY HAS A HOME</span><h2>Thank you for choosing to care.</h2><p>Every act of kindness reminds a child that they are seen, loved and not forgotten.</p><div><a href={campaignUrl} target="_blank" rel="noopener noreferrer" className="donate-primary">Donate online <ArrowRight size={17}/></a><a href="mailto:papaslovechildrenministry@gmail.com?subject=Donation%20to%20Papas%20Love" className="donate-outline">Ask us a question</a></div></div></section>

</main>}
